---
title: "WREG Output summary"
date: "`r Sys.time()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Summary text
```{r echo=FALSE}
print(wregOUT)
```

#Figures

##Fitted vs. Residuals

```{r echo=FALSE}
plot(wregOUT$fitted.values,wregOUT$residuals,
                        xlab="Fitted values",ylab="Residuals",
                        main="Fitted vs Residual")
```

##Y vs Leverage

```{r echo=FALSE}
plot(wregOUT$Y,wregOUT$ResLevInf$Leverage,
                          xlab="Y",ylab="Leverage",
                          main="Y vs Leverage")
                     abline(h=wregOUT$LevLim,lty=2,col="red")
                     par(mar=c(0, 0, 0, 0))
                     # c(bottom, left, top, right)
                     plot.new()
                     legend('center',"Critical value", lty = 2,
                            col="red",ncol=1,bty ="n")
```

##Y vs Influence

```{r echo=FALSE}
layout(rbind(1,2), heights=c(7,1))
                     plot(wregOUT$Y,wregOUT$ResLevInf$Influence,
                          xlab="Y",ylab="Influence",
                          main="Y vs Influence")
                     abline(h=wregOUT$InflLim,lty=2,col="red")
                     par(mar=c(0, 0, 0, 0))
                     # c(bottom, left, top, right)
                     plot.new()
                     legend('center',"Critical value", lty = 2,
                            col="red",ncol=1,bty ="n")
```

